<?php

namespace ContainerDZlUB5r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCallApiServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\CallApiService' shared autowired service.
     *
     * @return \App\Service\CallApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\CallApiService'] = new \App\Service\CallApiService(($container->privates['http_client'] ?? $container->load('getHttpClientService')));
    }
}
