<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJCxj7X\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJCxj7X/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerQJCxj7X.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerQJCxj7X\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerQJCxj7X\App_KernelDevContainer([
    'container.build_hash' => 'QJCxj7X',
    'container.build_id' => '80e30819',
    'container.build_time' => 1643195062,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQJCxj7X');
