<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD3N3lnW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD3N3lnW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD3N3lnW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD3N3lnW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD3N3lnW\App_KernelDevDebugContainer([
    'container.build_hash' => 'D3N3lnW',
    'container.build_id' => '9b432713',
    'container.build_time' => 1643198261,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD3N3lnW');
