<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLk9xFy6\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLk9xFy6/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerLk9xFy6.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerLk9xFy6\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerLk9xFy6\App_KernelProdDebugContainer([
    'container.build_hash' => 'Lk9xFy6',
    'container.build_id' => '4215ffb6',
    'container.build_time' => 1643125971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLk9xFy6');
