<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDZlUB5r\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDZlUB5r/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDZlUB5r.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDZlUB5r\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDZlUB5r\App_KernelProdContainer([
    'container.build_hash' => 'DZlUB5r',
    'container.build_id' => '3e29c521',
    'container.build_time' => 1643194900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDZlUB5r');
